#!/usr/bin/env python3
"""
Mock PersonalizedDocGenerator for testing staged execution
Simulates document generation
"""
import sys
import argparse
from pathlib import Path
from datetime import datetime

def main():
    parser = argparse.ArgumentParser(description="Mock PersonalizedDocGenerator")
    parser.add_argument('--mode', required=True)
    parser.add_argument('--topic', required=True)
    parser.add_argument('--audience', required=True)
    parser.add_argument('--type', required=True)
    parser.add_argument('--size', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--style', default='')
    parser.add_argument('--customer-story', default='')

    args = parser.parse_args()

    topic_path = Path(args.topic)
    if not topic_path.exists():
        print(f"Error: Topic file not found: {args.topic}", file=sys.stderr)
        return 1

    # Read topic file
    with open(topic_path, 'r') as f:
        topic_content = f.read()

    # Extract title
    title = "Test Document"
    for line in topic_content.split('\n'):
        if line.startswith('#'):
            title = line.lstrip('#').strip()
            break

    # Simulate document generation
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    doc_filename = f"{title.replace(' ', '_')[:50]}-{args.mode.upper()}-Generated.md"
    doc_path = output_dir / doc_filename

    doc_content = f"""# {title}

## Generated Document

This is a mock document generated from the topic: {title}

**Mode:** {args.mode}
**Audience:** {args.audience}
**Type:** {args.type}
**Size:** {args.size}

### Content

This document was generated by the mock PersonalizedDocGenerator for testing purposes.
In a real scenario, this would contain AI-generated content based on the topic insights.

### Test Information

- Generated at: {datetime.now().isoformat()}
- Topic file: {args.topic}
- Output directory: {args.output}

---
*Generated with Mock PersonalizedDocGenerator*
"""

    with open(doc_path, 'w') as f:
        f.write(doc_content)

    print(f"✓ Document generated: {doc_path}")

    return 0

if __name__ == "__main__":
    sys.exit(main())
